@startuml

start

:Получение заказа;

fork
  :Обработка платежа;
fork again
  :Подтверждение наличия товара;
end fork

:Синхронизация результатов платежа и наличия товара;

if (Платеж успешен и товар в наличии?) then (да)
  fork
    :Генерация счета;
  fork again
    :Подготовка заказа к отправке;
  end fork

  fork
    if (Требуется подарочная упаковка?) then (да)
      :Выполнение подарочной упаковки;
    else (нет)
      :Пропуск подарочной упаковки;
    endif
  fork again
    if (Выбор способа доставки?) then (экспресс)
      :Организация экспресс-доставки;
    else (стандарт)
      :Организация стандартной доставки;
    endif
  end fork

  :Отправка уведомления клиенту о статусе заказа;
else (нет)
  if (Платеж неудачен?) then (да)
    :Уведомление клиента о проблемах с оплатой;
  else (нет)
    :Уведомление клиента о недоступности товара;
  endif
endif

stop
@enduml
